### ISSUE TITLE
infografia calidad de software

### ISSUE THREAD

**Issue by carlos-chrs** [Near-University-Tec-de-Tlaxiaco/horizon#1]
[INFOGRAFIA_CALIDAD DE SOFTWARE_CARLOS CHRISTIAN HERNANDEZ MATRA.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/horizon/files/8864622/INFOGRAFIA_CALIDAD.DE.SOFTWARE_CARLOS.CHRISTIAN.HERNANDEZ.MATRA.pdf)

**Comment by Rosa218** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
