### ISSUE TITLE
Infografia Calidad de Software

### ISSUE THREAD

**Issue by AndreLuna6** [Near-University-Tec-de-Tlaxiaco/horizon#2]
[InfografiaCDS_AndreEmmanuelLunaGonzalez.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/horizon/files/8894244/InfografiaCDS_AndreEmmanuelLunaGonzalez.pdf)

**Comment by Rosa218** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
