### ISSUE TITLE
Practica_Pruebas_Unitarias

### ISSUE THREAD

**Issue by carlos-chrs** [Near-University-Tec-de-Tlaxiaco/horizon#3]
[PruebasUnitarias_Horizon.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/horizon/files/8895843/PruebasUnitarias_Horizon.pdf)

**Comment by bg55-a** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
