### ISSUE TITLE
Falta en el archivo readme.ME el llamado a contratos inteligentes

### ISSUE THREAD

**Issue by josealfredo79** [Near-University-Tec-de-Tlaxiaco/horizon#4]
![image](https://user-images.githubusercontent.com/58342642/174460108-a466d080-b73b-46bb-be1d-3d35ea2fd71c.png)
 Se deben incluir las llamadas a los contratos inteligentes...

**Comment by carlos-chrs** [comment]
ya quedo Ing. por favor de revisar.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
